// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmk3r_6zFzgucNHw-9fp58AOjIITPmS54',
    appId: '1:642153504200:web:634674c2e5c59faa2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    authDomain: 'project6-a1c9a.firebaseapp.com',
    storageBucket: 'project6-a1c9a.appspot.com',
    measurementId: 'G-73C48ZXGCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfUHW1m_dYCJGLsUnV5yqUrRvIPOUSo0',
    appId: '1:642153504200:android:71237af5fa4fb8b82434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpopVyZSmloyow1lfpGUxgjC4vDvlP9F0',
    appId: '1:642153504200:ios:027d266dd7f2e8eb2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.appspot.com',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpopVyZSmloyow1lfpGUxgjC4vDvlP9F0',
    appId: '1:642153504200:ios:027d266dd7f2e8eb2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.appspot.com',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmk3r_6zFzgucNHw-9fp58AOjIITPmS54',
    appId: '1:642153504200:web:e31fe0a33c2065812434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    authDomain: 'project6-a1c9a.firebaseapp.com',
    storageBucket: 'project6-a1c9a.appspot.com',
    measurementId: 'G-SD2KHTW7YC',
  );
}
